version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  auth:
    build: ./auth-service
    container_name: auth_service
    restart: always
    environment:
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=main_db
      - DB_USER=devuser
      - DB_PASS=devpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data: